#!/bin/bash

# Stash changes before running tests
git stash -q --keep-index

# Run your unit tests
echo "Running unit tests..."
# Replace the following line with your actual test command
# For example, if you're using a test runner like pytest:
# pytest

./gradlew spotlessCheck

# Check the exit status of the test command
if [ $? -ne 0 ]; then
    echo "Spotless Linter failed. Stopping commit."
    
    # Restore the workspace to pre-commit state
    git stash pop -q

    exit 1
fi

./gradlew test

# Check the exit status of the test command
if [ $? -ne 0 ]; then
    echo "Unit tests failed. Stopping commit."
    
    # Restore the workspace to pre-commit state
    git stash pop -q

    exit 1
fi

# If tests pass, pop the stash
git stash pop -q

# Continue with the commit
exit 0